//
// Created by eyal on 12.1.2020.
//

#ifndef SEARCHING_ALGORITHM_SERVER_CACHEMANAGER_H
#define SEARCHING_ALGORITHM_SERVER_CACHEMANAGER_H

class CacheManager {

};

#endif //SEARCHING_ALGORITHM_SERVER_CACHEMANAGER_H
