//
// Created by eyal on 12.1.2020.
//

#ifndef SEARCHING_ALGORITHM_SERVER_FILECACHEMANAGER_H
#define SEARCHING_ALGORITHM_SERVER_FILECACHEMANAGER_H

class FileCacheManager {

};

#endif //SEARCHING_ALGORITHM_SERVER_FILECACHEMANAGER_H
