//
// Created by yair on 12/01/2020.
//

#ifndef SEARCHING_ALGORITHM_SERVER_MYSERIALSERVER_H
#define SEARCHING_ALGORITHM_SERVER_MYSERIALSERVER_H


class MySerialServer {

};


#endif //SEARCHING_ALGORITHM_SERVER_MYSERIALSERVER_H
