//
// Created by eyal on 12.1.2020.
//

#ifndef SEARCHING_ALGORITHM_SERVER_MYTESTCLIENTHANDLER_H
#define SEARCHING_ALGORITHM_SERVER_MYTESTCLIENTHANDLER_H

class MyTestClientHandler {

};

#endif //SEARCHING_ALGORITHM_SERVER_MYTESTCLIENTHANDLER_H
